vdc_host:
  dSUID: 000000007F9202F411B8B5822402000000
  type: vDChost
  name: vDC Test Server
  model: TestServer
  model_uid: clean_script
  model_version: 0.8B
  vendor_id: KarlKiel
  api_version: '2.0'
vdcs: {}
vdsds: {}
