vdc_host:
  dSUID: 000000007F9202F411B8B5822402000000
  type: vDChost
  name: vDC Test Server
  model: TestServer
  model_uid: clean_script
  model_version: 0.8B
  vendor_id: KarlKiel
  api_version: '2.0'
vdcs:
  000000017F9202F411B8B5822402000000:
    dSUID: 000000017F9202F411B8B5822402000000
    type: vDC
    model: KarlKiel
    modelUID: karlkiel
    vendorName: KarlKiel
    name: testVdc
    active: true
    displayId: ''
    modelVersion: '1.0'
    implementationId: x-KarlKiel-generic vDC
    capabilities:
      metering: false
      identification: false
      dynamicDefinitions: true
    zoneID: 65534
vdsds: {}
