vdc_host:
  dSUID: 00000000990505A09E9E6D8AC211000000
  type: vDChost
  name: Test Host
  model: vDC Host
  model_uid: vdc-host
  model_version: '1.0'
  vendor_id: KarlKiel
  api_version: '2.0'
vdcs: {}
vdsds: {}
